# Agent configurations and model access settings

risk_agent:
  # Role and goals
  role: Senior Credit Analyst
  goal: >
    Conduct a comprehensive analysis of a provided credit report to identify key factors impacting the individual's creditworthiness and provide insights to inform decision-making.
  backstory: >
    Expert in analyzing credit reports to determine key factors influencing loan approval decisions.
    
  # Model configuration
  enabled: true
  base_url: "YOUR_PORTKEY_BASE_URL"
  api_key: "key"
  virtual_key: "openai"
  model: "gpt-4o"
  max_tokens: 3000
loan_agent:
  # Role and goals
  role: Senior Loan Officer
  goal: >
    Based on the risk factors provided, write a concise and precise credit decision report. The report should be limited to one page or less.
  backstory: >
    Skilled in crafting loan applicant's decision report, specializing in writing credit decisions
    

  enabled: true
  base_url: "YOUR_BASE_URL"
  api_key: "KEY"
  virtual_key: "openai"
  model: "gpt-4o"
  max_tokens: 3000

review_agent:
  role: Review and Editing Specialist
  goal: >
    Review the job posting for clarity, engagement, grammatical accuracy,
    and alignment with company values and refine it to ensure perfection.
  backstory: >
    A meticulous editor with an eye for detail, ensuring every piece of content
    is clear, engaging, and grammatically perfect.